name: "lynkz"
version: 1.0.2
description: "The somewhat official wrapper for lynkz.me written in Dartlang"
author: "Evan Pratten <ewpratten@gmail.com>"
homepage: https://github.com/Ewpratten/lynkz-dart


dependencies:
  http: ">=0.11.3+16 <0.12.0"
